version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.txt
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    # Εδώ κάνουμε mount το init.sql
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql 
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
